### ISSUE TITLE
How to renew a wildcard certificate?

### ISSUE THREAD

**Issue by Tealons** [fszlin/certes#110]
I just succeeded in creating my first wildcard certificate for an Azure Web App. The docs are telling me how to create a certificate, but not how to do the renewal. Can tell me what to do to renew the certificate? I’m aiming to create a webjob to do this automatically.

**Comment by fszlin** [comment]
The idea is to generate a new certificate every 3 months, reuse your account key if possible.

I'd suggest doing so as a [scheduled build](https://github.com/fszlin/lo0.in/blob/master/.appveyor.yml#L57). 😄

**Comment by Tealons** [comment]
I saw the script and tried to run the commands in powershell on Kudo, but got stuck. I have no experience with Appveryor. How can I run the script on a Azure Web App?

**Comment by TraGicCode** [comment]
@fszlin

When you renew the certs I guess the dns txt records don’t change or are an ignored step.  Can u explain this in more detail.  My understanding is that once you verify ownership of a domain you simply use the generated key pair to ask let’s encrypt for renewals in the future and no updating dns txt records is needed

**Comment by webprofusion-chrisc** [comment]
Hi, when you renew a certificate with Let's Encrypt you are actually requesting a whole new cert for the same domains, so renewal requires repeating the validation challenge process again. 

For DNS challenges this involves create the _acme-challenge TXT record in your domain or subdomain, with the value derived from the authorization specified by Let's Encrypt. 

If your cert has multiple domains included then you need to create multiple TXT records in each respective DNS zone.

Note: Certs with wildcard + the root domain (e.g. *.example.com and example.com) require that the TXT record has 2 values in order to respond to the authorization challenge for each part.
